### ISSUE TITLE
EXCEPTION: Error in ./FormComponent class FormComponent - inline template:8:4 caused by: No provider for Form!

### ISSUE THREAD

**Issue by byzg** [raychenfj/ion-multi-picker#16]
Hi, I've just run `npm install ion-multi-picker --save` and put it to my app.module.ts : 
```typescript
import  { NgModule }                    from '@angular/core';
import  { IonicApp, IonicModule }       from 'ionic-angular';
import  { NgbModule }                   from '@ng-bootstrap/ng-bootstrap';
import  { Http }                        from '@angular/http';
import  { TranslateModule,
          TranslateLoader,
          MissingTranslationHandler }   from 'ng2-translate';
import  { MultiPickerModule }           from 'ion-multi-picker';

import  { createTranslateLoader,
          MyMissingTranslationHandler } from '../config/i18n'
...
import  { NewTimesheet }  from './components/pages/timesheets/new/new';
...

@NgModule({
  declarations: [
    App,
    Timesheets,
    NewTimesheet.FormComponent
    ...
  ],
  imports: [
    NgbModule.forRoot(),
    IonicModule.forRoot(App),
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (createTranslateLoader),
      deps: [Http]
    }),
    MultiPickerModule
  ],
  entryComponents: [
    App,
    Timesheets,
    NewTimesheet.FormComponent
    ...
  ],
  providers: [
    ...
  ],
  bootstrap: [IonicApp]
})
export class AppModule {}

```

and component is: 
```typescript
import { Component } from '@angular/core';
import { NavParams } from 'ionic-angular';
...

export namespace NewTimesheet {
  ...

  @Component({
    selector: 'timesheets-new-form',
    templateUrl: 'form.html'
  })
  export class FormComponent {
    ...
    timesheet: Timesheet;

    simpleColumns: Array<Object>;

    constructor() {
      this.simpleColumns = [
        {
          name: 'col1',
          options: [{ text: '1', value: '1' },
            { text: '2', value: '2' },
            { text: '3', value: '3' }]
        },
        {
          name: 'col2',
          options: [{ text: '1-1', value: '1-1' },
            { text: '1-2', value: '1-2' },
            { text: '2-1', value: '2-1' },
            { text: '2-2', value: '2-2' },
            { text: '3-1', value: '3-1' },]
        },
        {
          name: 'col3',
          options: [{ text: '1-1-1', value: '1-1-1' },
            { text: '1-1-2', value: '1-1-2' },
            { text: '1-2-1', value: '1-2-1' },
            { text: '1-2-2', value: '1-2-2' },
            { text: '2-1-1', value: '2-1-1' },
            { text: '2-1-2', value: '2-1-2' },
            { text: '2-2-1', value: '2-2-1' },
            { text: '2-2-2', value: '2-2-2' },
            { text: '3-1-1', value: '3-1-1' },
            { text: '3-1-2', value: '3-1-2' },]
        }
      ];
    }
  }
}

```

and view is 

```html
<ion-header>
  <ion-navbar>
    <ion-title>Simple Example</ion-title>
  </ion-navbar>
</ion-header>
<ion-content padding class="simple">
  <ion-item>
    <ion-label>Simple Picker</ion-label>
    <ion-multi-picker  id='simple' item-content [multiPickerColumns]="simpleColumns"></ion-multi-picker>

  </ion-item>
</ion-content>
```

but when I try to go to the view I get an error in the browser console and page is blank:
```
Uncaught TypeError: Cannot read property 'create' of undefined(anonymous function) @ measureIt.js:120
error_handler.js:48 EXCEPTION: Error in ./FormComponent class FormComponent - inline template:8:4 caused by: No provider for Form!ErrorHandler.handleError @ error_handler.js:48next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81NgZone.triggerError @ ng_zone.js:280onHandleError @ ng_zone.js:259t.handleError @ polyfills.js:3e.runGuarded @ polyfills.js:3NgZone.runGuarded @ ng_zone.js:133outsideHandler @ dom_events.js:30t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3
error_handler.js:50 ORIGINAL EXCEPTION: No provider for Form!ErrorHandler.handleError @ error_handler.js:50next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81NgZone.triggerError @ ng_zone.js:280onHandleError @ ng_zone.js:259t.handleError @ polyfills.js:3e.runGuarded @ polyfills.js:3NgZone.runGuarded @ ng_zone.js:133outsideHandler @ dom_events.js:30t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3
error_handler.js:53 ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:53next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81NgZone.triggerError @ ng_zone.js:280onHandleError @ ng_zone.js:259t.handleError @ polyfills.js:3e.runGuarded @ polyfills.js:3NgZone.runGuarded @ ng_zone.js:133outsideHandler @ dom_events.js:30t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3
error_handler.js:54 Error: No provider for Form!
    at NoProviderError.Error (native)
    at NoProviderError.BaseError [as constructor] (/home/myApp/node_modules/@angular/core/src/facade/errors.js:27:34)
    at NoProviderError.AbstractProviderError [as constructor] (/home/myApp/node_modules/@angular/core/src/di/reflective_errors.js:53:16)
    at new NoProviderError (/home/myApp/node_modules/@angular/core/src/di/reflective_errors.js:84:16)
    at ReflectiveInjector_._throwOrNull (/home/myApp/node_modules/@angular/core/src/di/reflective_injector.js:775:19)
    at ReflectiveInjector_._getByKeyDefault (/home/myApp/node_modules/@angular/core/src/di/reflective_injector.js:803:25)
    at ReflectiveInjector_._getByKey (/home/myApp/node_modules/@angular/core/src/di/reflective_injector.js:766:25)
    at ReflectiveInjector_.get (/home/myApp/node_modules/@angular/core/src/di/reflective_injector.js:575:21)
    at NgModuleInjector.get (/home/myApp/node_modules/@angular/core/src/linker/ng_module_factory.js:102:52)
    at ElementInjector.get (/home/myApp/node_modules/@angular/core/src/linker/element_injector.js:31:48)ErrorHandler.handleError @ error_handler.js:54next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81NgZone.triggerError @ ng_zone.js:280onHandleError @ ng_zone.js:259t.handleError @ polyfills.js:3e.runGuarded @ polyfills.js:3NgZone.runGuarded @ ng_zone.js:133outsideHandler @ dom_events.js:30t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3
error_handler.js:57 ERROR CONTEXT:ErrorHandler.handleError @ error_handler.js:57next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81NgZone.triggerError @ ng_zone.js:280onHandleError @ ng_zone.js:259t.handleError @ polyfills.js:3e.runGuarded @ polyfills.js:3NgZone.runGuarded @ ng_zone.js:133outsideHandler @ dom_events.js:30t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3
error_handler.js:58 DebugContext {_view: _View_FormComponent0, _nodeIndex: 16, _tplRow: 8, _tplCol: 4}ErrorHandler.handleError @ error_handler.js:58next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81NgZone.triggerError @ ng_zone.js:280onHandleError @ ng_zone.js:259t.handleError @ polyfills.js:3e.runGuarded @ polyfills.js:3NgZone.runGuarded @ ng_zone.js:133outsideHandler @ dom_events.js:30t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3
polyfills.js:3 Uncaught Error: Error in ./FormComponent class FormComponent - inline template:8:4 caused by: No provider for Form!
```

my package.json:
```json
{
  "name": "myApp",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.10",
    "@ngrx/core": "^1.2.0",
    "@ngrx/store": "^2.2.1",
    "@types/humps": "^1.1.2",
    "@types/lodash": "^4.14.38",
    "@types/pluralize": "0.0.27",
    "@types/qs": "^6.2.30",
    "humps": "^2.0.0",
    "ion-multi-picker": "^1.0.8",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.6",
    "ionicons": "3.0.0",
    "ng2-http-interceptor": "^0.4.0",
    "ng2-translate": "^4.0.0",
    "pluralize": "^3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.45",
    "typescript": "^2.0.3"
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "description": "An Ionic project"
}

```

Have you any idea how to solve it?

**Comment by raychenfj** [comment]
Hi @byzg ,
I believe this error is not relate to the multi picker component. 
You can try to remove the `ion-multi-picker` package and see if the error still remains.

Besides , there are severval things I noticed in your code:
1. When you import the ngModule, you make a typo, `NgbModule.forRoot()`
2. From your component's name, I guess you maybe use angular form , which it's not pasted here, if so please try to import angular forms module.
```
import { FormsModule }   from '@angular/forms';
...
@NgModule({
  imports: [
    BrowserModule,
    FormsModule
  ]
...
}
```

Hope it help.

**Comment by byzg** [comment]
@raychenfj  I've removed ion-multi-picker and all it using of it and the error disappeared. Next I've created new ionic project and added to it ion-multi-picker, it was working fine. Next I've added  ion-multi-picker to the first project again and it's so strange but now it is working. I dont know how but now it's ok.
There is only one thing: console.debug is still present.
Thanks

**Comment by Charleschu8** [comment]
@byzg ,I think you maybe use old project to install ion-multi-picker, this component just can run Ionic Framework Version: 2.0.0-rc.3" version.  you can confirm your previous project ( ionic info). :)
