### ISSUE TITLE
Local installation/build failed

### ISSUE THREAD

**Issue by ryaa** [raychenfj/ion-multi-picker#97]
I cloned the repository and tried to run npm install however I'm getting the below error when the code from the cloned repository is built

```
> ion-multi-picker@2.1.2 build /Users/alexryltsov/Git/ION-MULTI-PICKER/master
> gulp

[13:29:25] Using gulpfile ~/Git/ION-MULTI-PICKER/master/gulpfile.js
[13:29:25] Starting 'default'...
[13:29:25] Starting 'del'...
[13:29:25] Finished 'default' after 4.19 ms
[13:29:25] Finished 'del' after 13 ms
[13:29:25] Starting 'copyhtml'...
[13:29:25] Finished 'copyhtml' after 3.81 ms
[13:29:25] Starting 'copyscss'...
[13:29:25] Finished 'copyscss' after 445 μs
[13:29:25] Starting 'ngc'...
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:30: ',' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:47: ';' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:68: 'ReadonlyArray' only refers to a type, but is being used as a value here.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:90: '(' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:92: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:94: Cannot find name 'methodName'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:104: ']' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:106: Cannot find name 'string'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:112: ',' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:113: Property assignment expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:121: ')' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:124: 'ReadonlyArray' only refers to a type, but is being used as a value here.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:147: '(' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:149: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:150: A computed property name must be of type 'string', 'number', 'symbol', or 'any'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:151: Cannot find name 'P'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:156: Cannot find name 'keyof'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:162: ']' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:162: Cannot find name 'T'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:163: ',' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:164: Property assignment expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:165: Property assignment expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:179: ',' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:180: Cannot find name 'P'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:183: ':' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:208: '{' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:217: ':' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:217: Cannot find name 'T'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:219: Cannot find name 'P'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:222: ',' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:224: An object literal cannot have multiple properties with the same name in strict mode.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:227: ':' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:228: Expression expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:230: ')' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:157:58: Generic type 'SpyObjMethodNames' requires 2 type argument(s).
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:158:61: Generic type 'SpyObjMethodNames' requires 2 type argument(s).
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:160:40: Generic type 'SpyObjMethodNames' requires 2 type argument(s).
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:161:43: Generic type 'SpyObjMethodNames' requires 2 type argument(s).
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:575:13: Invalid use of 'arguments'. Modules are automatically in strict mode.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:635:30: ';' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:635:49: Cannot find name 'T'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:635:51: Cannot find name 'k'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:635:56: 'Spy' only refers to a type, but is being used as a value here.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:635:62: Cannot find name 'T'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:635:64: Cannot find name 'k'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:642:24: Cannot find name 'Spy'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:644:32: Cannot find name 'Spy'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:646:41: Cannot find name 'Spy'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:648:33: Cannot find name 'Spy'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:650:34: Cannot find name 'Spy'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:652:17: Cannot find name 'Spy'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:691:37: Cannot find name 'Reporter'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:697:21: Cannot find name 'RunDetails'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:701:19: Cannot find name 'Suite'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:702:33: Cannot find name 'SuiteOrSpec'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:711:15: Cannot find name 'Spec'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:712:16: Cannot find name 'Clock'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:716:30: Cannot find name 'HtmlReporter'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:717:32: Cannot find name 'HtmlSpecFilter'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:720:1: Declaration or statement expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/m[13:29:35] 'ngc' errored after 10 s
[13:29:35] Error: Command `ngc -p ./config/tsconfig.build.json` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
[13:29:35] Error in plugin 'run-sequence(ngc)'
Message:
    Command `ngc -p ./config/tsconfig.build.json` failed with exit code 1
Details:
    killed: false
    code: 1
    signal: null
    cmd: ngc -p ./config/tsconfig.build.json
    stdout:
    stderr: Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:30: ',' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:47: ';' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:68: 'ReadonlyArray' only refers to a type, but is being used as a value here.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:90: '(' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:92: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:94: Cannot find name 'methodName'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:104: ']' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:106: Cannot find name 'string'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:112: ',' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:113: Property assignment expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:121: ')' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:124: 'ReadonlyArray' only refers to a type, but is being used as a value here.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:147: '(' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:149: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:150: A computed property name must be of type 'string', 'number', 'symbol', or 'any'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:151: Cannot find name 'P'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:156: Cannot find name 'keyof'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:162: ']' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:162: Cannot find name 'T'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:163: ',' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:164: Property assignment expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:165: Property assignment expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:179: ',' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:180: Cannot find name 'P'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:183: ':' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:208: '{' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:217: ':' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:217: Cannot find name 'T'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:219: Cannot find name 'P'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:222: ',' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:224: An object literal cannot have multiple properties with the same name in strict mode.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:227: ':' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:228: Expression expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:142:230: ')' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:157:58: Generic type 'SpyObjMethodNames' requires 2 type argument(s).
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:158:61: Generic type 'SpyObjMethodNames' requires 2 type argument(s).
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:160:40: Generic type 'SpyObjMethodNames' requires 2 type argument(s).
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:161:43: Generic type 'SpyObjMethodNames' requires 2 type argument(s).
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:575:13: Invalid use of 'arguments'. Modules are automatically in strict mode.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:635:30: ';' expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:635:49: Cannot find name 'T'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:635:51: Cannot find name 'k'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:635:56: 'Spy' only refers to a type, but is being used as a value here.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:635:62: Cannot find name 'T'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:635:64: Cannot find name 'k'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:642:24: Cannot find name 'Spy'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:644:32: Cannot find name 'Spy'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:646:41: Cannot find name 'Spy'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:648:33: Cannot find name 'Spy'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:650:34: Cannot find name 'Spy'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:652:17: Cannot find name 'Spy'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:691:37: Cannot find name 'Reporter'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:697:21: Cannot find name 'RunDetails'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:701:19: Cannot find name 'Suite'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:702:33: Cannot find name 'SuiteOrSpec'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:711:15: Cannot find name 'Spec'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:712:16: Cannot find name 'Clock'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:716:30: Cannot find name 'HtmlReporter'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:717:32: Cannot find name 'HtmlSpecFilter'.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/master/node_modules/@types/jasmine/index.d.ts:720:1: Declaration or statement expected.
Error at /Users/alexryltsov/Git/ION-MULTI-PICKER/m
Stack:
Error: Command `ngc -p ./config/tsconfig.build.json` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ion-multi-picker@2.1.2 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ion-multi-picker@2.1.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexryltsov/.npm/_logs/2019-11-14T10_29_35_493Z-debug.log
```

Here are the environment details
```
System:

   NodeJS : v10.16.2
   npm    : 6.9.0
   OS     : macOS Catalina
```

**Comment by ryaa** [comment]
The problem is that some libraries introduced breaking changes (specifically jasmine which is required by protractor and lodash required by couple other packages) which required to use newer version of typescript (see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30310).
Since there was no package-lock.json file in the repository when I cloned the repo and run npm install I got newer jasmine and lodash packages which broken the build. I downgraded those packages to be compatible with the typescript version used in this package.

Please note that upgrading typescript will require to upgrade ionic and bunch of other packages. It would be helpful to make such an upgrade though.

**Comment by raychenfj** [comment]
Hi @ryaa ,

Thanks for reminding.  Since there is no lock file in the old day. I will add one.
